batch_size: 256
config_type: correlation
cutout: false
cutout_length: 16
cutout_prob: 1.0
dataset: cifar10
out_dir: run
predictor: SiGeo
search_space: nasbench101
seed: 9000
test_size: 1000
train_portion: 0.7
start_idx: 0
n_models: 1000